### ISSUE TITLE
Gitcoin Bounty

### ISSUE THREAD

**Issue by Toananh1998** [XDC-Community/docs#9]
This is the GitHub issue template dedicated for the Gitcoin bounty set up by the XDC Community.  The bounty will have specific requirements the contributor must follow to be considered for the bounty.  Please see specific requirements. 

## **Judging Criteria**

All submissions must contain clear and concise information with explicit instruction and images describing each step required to execute the process.  An accompanying video in addition to the written content is highly desired.

All submissions will be put through an industry standard plagiarism detection tool to ensure that all submissions are the work and ideas of the person submitting for the bounty.  If the plagiarism tools flags your submission you will be disqualified from participation in the bounty.

You will be provided with resources (if available) as an aid to help you get started.  The sole act of submitting content for the bounty does not automatically qualify you for the bounty.  Our team will review all submissions and will choose the submission whose content best fits the needs and requirements of the bounty.

Participants that are selected as winners for the bounty will be notified within 7 working days after the bounty has ended.

## **Amount of Bounty**
Foundry Grant. All monies paid will be in XDC.

## **What will you be creating?**
You will be creating how to documentation for the XDC Network. Some documentation has already been created, and you will read through it to ensure it works as intended, reads clearly or if it needs better clarfication, then make those changes. Those items without documentation will be created from scratch.  Documentation will have images that describe or represents what's being done or described in your tutorial. 

## *Name or title of the tutorial*
  - Overview
    Here you can write the overview of what the tutorial will be about.
  ## *What you will learn*
   For example: In this tutorial, you will learn how to set up (insert name of tutorial) and use it to build, test and deploy a simple smart contract.
  ## *What you will do*
   - Set up (Name of tool(s) you will be setting up)
   - Create a simple smart contract
   - Compile contract
   - Test contract
   - Deploy contract
      
## **Setting up the development environment**
   - Creating a project (with images)
   - Checking the contract (sample code with images preferred)
   - Setting up the contract
   - Compiling the contract
   - Testing the contract (where is the contract going to be tested...a link will be great)
    
## **Deploying a contract on the XDC Network**
This section can be used if you are deploying contracts on the network. Otherwise it can be ommited when you create your bounty. 
    
## **Total Prize of Bounty**
Total sum of up to $X,XXX worth of XDC for this event.

Each submission will be paid according to the amount of work submitted. Only one winner will be chosen and announced within 7 working days after bounty has expired.  

## **Further Details**
This event will be an ongoing collaboration to create "how to" documentation for the XDC Network. All documentation will be open source and uploaded here: 

(insert link for either github, gitbooks, etc)

## **Resources**
These are some of the resources you have available to you where you will find the necessary information to complete your submission.

## **XDC Remix**
https://remix.xinfin.network/#optimize=false&runs=200&evmVersion=null&version=soljson-v0.8.7+commit.e28d00a7.js

## **Sample of Documentation**
(Please add links to documentation here)

**Comment by Tpada13** [comment]
This is not a bounty from XDC Community.
